### ISSUE TITLE
Implement authentication with schulcloud-server

### ISSUE THREAD

**Issue by kremer-io** [schul-cloud/schulcloud-content#4]
Crawlers can authenticate with username and password (Basic Auth). The schulcloud-content service should forward the credentials to the schulcloud-server and may cache the "session".

- [ ] Forward authentication
- [ ] Cache Session

**Comment by niccokunzmann** [comment]
@kremer-io This is done, right?

**Comment by kremer-io** [comment]
@niccokunzmann yes
